### ISSUE TITLE
Height value for Long Rest dialogue box needs to be set correctly

### ISSUE THREAD

**Issue by IrateRedKite** [Lazrius/FoundryVTT-Module-LaziQol#1]
Long rest box is, by default, slightly too small. The height value needs to be set dynamically, or removed.

![image](https://user-images.githubusercontent.com/12358715/160244972-a88b65ab-f3e5-4dce-8f95-1d3aa989c4fc.png)

**Comment by Lazrius** [comment]
Implemented in release v1.0.3 ([9d9c83b](https://github.com/Lazrius/FoundryVTT-Module-LaziQol/commit/9d9c83b5a7516751111ddd6aa6fe624be003eed3))
