### ISSUE TITLE
Non-prepared casters still have the option to remove all spells!

### ISSUE THREAD

**Issue by IrateRedKite** [Lazrius/FoundryVTT-Module-LaziQol#2]
If data.details.maxPreparedSpells is not set, ensure that the 'reset prepared spells' checkbox is not available in the long rest dialogue.

**Comment by Lazrius** [comment]
Implemented in release v1.0.3 ([9d9c83b](https://github.com/Lazrius/FoundryVTT-Module-LaziQol/commit/9d9c83b5a7516751111ddd6aa6fe624be003eed3))
