### ISSUE TITLE
Prevent prepared casters from preparing more spells than data.details.maxPreparedSpells

### ISSUE THREAD

**Issue by IrateRedKite** [Lazrius/FoundryVTT-Module-LaziQol#3]
If casters are at their maximum number of prepared spells, set by `data.details.maxPreparedSpells`, they should not be able to prepare more! If a caster is at max spells and tries to prepare another, the button should not respond, and there should be a small ui notification informing the user they have prepared the maximum number of spells available to them.

**Comment by Lazrius** [comment]
Implemented in release v1.0.3 ([9d9c83b](https://github.com/Lazrius/FoundryVTT-Module-LaziQol/commit/9d9c83b5a7516751111ddd6aa6fe624be003eed3))
